services:
  # Nginx反向代理 - HTTPS支持
  nginx:
    image: dockerpull.pw/nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - api-server
      - game-server
    networks:
      - boardgame-network

  # 前端应用 - 包含boardgame.io客户端
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_SERVER: https://192.168.1.156/games
        REACT_APP_API_SERVER: https://192.168.1.156
    image: localhost/hqit/boardgame-frontend:latest
    expose:
      - "3000"
    environment:
      - REACT_APP_SERVER=https://192.168.1.156/games
      - REACT_APP_API_SERVER=https://192.168.1.156
    networks:
      - boardgame-network

  # boardgame.io游戏服务器 - 专门处理游戏逻辑
  game-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: localhost/hqit/boardgame-server:latest
    expose:
      - "8000"
    environment:
      - NODE_ENV=development
    networks:
      - boardgame-network

  # API服务器 - 专门处理业务逻辑（认证、AI等）
  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    image: localhost/hqit/boardgame-api-server:latest
    expose:
      - "8001"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_NAME=boardgame_db
      - DB_USER=boardgame_user
      - DB_PASSWORD=boardgame_pass
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - ADMIN_PASSWORD=admin123
    depends_on:
      - postgres
      - redis
    networks:
      - boardgame-network

  # PostgreSQL数据库 - 生产环境使用
  postgres:
    image: dockerpull.pw/postgres:15-alpine
    environment:
      - POSTGRES_DB=boardgame_db
      - POSTGRES_USER=boardgame_user
      - POSTGRES_PASSWORD=boardgame_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - boardgame-network

  # Redis缓存 - 会话和房间状态
  redis:
    image: dockerpull.pw/redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - boardgame-network

volumes:
  postgres_data:
  redis_data:

networks:
  boardgame-network:
    driver: bridge 